### ISSUE TITLE
Should be marked as Client or Server on modrinth?

### ISSUE THREAD

**Issue by Kirisoup** [AmyMialeeMods/potionparticlepack#3]
It seems like that this mod need to be also installed server-side for the multiple particle colours feature to work properly.

**Comment by AmyMialee** [comment]
I have it as optional server rn but it might make sense to make it marked as required given how it's the main feature.
![image](https://github.com/AmyMialeeMods/potionparticlepack/assets/10999535/7f5de665-2346-45c7-bda5-8f173c871869)
The other stuff works fine but yk I assume most people aren't downloading for those.
What do you think would be best?

**Comment by AmyMialee** [comment]
no replies
